/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alianca.intercab.emp.quotation;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AssociatedProductInstancesAVRO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4315868971032893101L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AssociatedProductInstancesAVRO\",\"namespace\":\"com.alianca.intercab.emp.quotation\",\"fields\":[{\"name\":\"quotationProductId\",\"type\":\"long\"},{\"name\":\"instancesId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AssociatedProductInstancesAVRO> ENCODER =
      new BinaryMessageEncoder<AssociatedProductInstancesAVRO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AssociatedProductInstancesAVRO> DECODER =
      new BinaryMessageDecoder<AssociatedProductInstancesAVRO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AssociatedProductInstancesAVRO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AssociatedProductInstancesAVRO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AssociatedProductInstancesAVRO>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AssociatedProductInstancesAVRO to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AssociatedProductInstancesAVRO from a ByteBuffer. */
  public static AssociatedProductInstancesAVRO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long quotationProductId;
  @Deprecated public long instancesId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AssociatedProductInstancesAVRO() {}

  /**
   * All-args constructor.
   * @param quotationProductId The new value for quotationProductId
   * @param instancesId The new value for instancesId
   */
  public AssociatedProductInstancesAVRO(java.lang.Long quotationProductId, java.lang.Long instancesId) {
    this.quotationProductId = quotationProductId;
    this.instancesId = instancesId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return quotationProductId;
    case 1: return instancesId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: quotationProductId = (java.lang.Long)value$; break;
    case 1: instancesId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'quotationProductId' field.
   * @return The value of the 'quotationProductId' field.
   */
  public java.lang.Long getQuotationProductId() {
    return quotationProductId;
  }

  /**
   * Sets the value of the 'quotationProductId' field.
   * @param value the value to set.
   */
  public void setQuotationProductId(java.lang.Long value) {
    this.quotationProductId = value;
  }

  /**
   * Gets the value of the 'instancesId' field.
   * @return The value of the 'instancesId' field.
   */
  public java.lang.Long getInstancesId() {
    return instancesId;
  }

  /**
   * Sets the value of the 'instancesId' field.
   * @param value the value to set.
   */
  public void setInstancesId(java.lang.Long value) {
    this.instancesId = value;
  }

  /**
   * Creates a new AssociatedProductInstancesAVRO RecordBuilder.
   * @return A new AssociatedProductInstancesAVRO RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder newBuilder() {
    return new com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder();
  }

  /**
   * Creates a new AssociatedProductInstancesAVRO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AssociatedProductInstancesAVRO RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder newBuilder(com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder other) {
    return new com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder(other);
  }

  /**
   * Creates a new AssociatedProductInstancesAVRO RecordBuilder by copying an existing AssociatedProductInstancesAVRO instance.
   * @param other The existing instance to copy.
   * @return A new AssociatedProductInstancesAVRO RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder newBuilder(com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO other) {
    return new com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder(other);
  }

  /**
   * RecordBuilder for AssociatedProductInstancesAVRO instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AssociatedProductInstancesAVRO>
    implements org.apache.avro.data.RecordBuilder<AssociatedProductInstancesAVRO> {

    private long quotationProductId;
    private long instancesId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.quotationProductId)) {
        this.quotationProductId = data().deepCopy(fields()[0].schema(), other.quotationProductId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.instancesId)) {
        this.instancesId = data().deepCopy(fields()[1].schema(), other.instancesId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AssociatedProductInstancesAVRO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.quotationProductId)) {
        this.quotationProductId = data().deepCopy(fields()[0].schema(), other.quotationProductId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.instancesId)) {
        this.instancesId = data().deepCopy(fields()[1].schema(), other.instancesId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'quotationProductId' field.
      * @return The value.
      */
    public java.lang.Long getQuotationProductId() {
      return quotationProductId;
    }

    /**
      * Sets the value of the 'quotationProductId' field.
      * @param value The value of 'quotationProductId'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder setQuotationProductId(long value) {
      validate(fields()[0], value);
      this.quotationProductId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'quotationProductId' field has been set.
      * @return True if the 'quotationProductId' field has been set, false otherwise.
      */
    public boolean hasQuotationProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'quotationProductId' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder clearQuotationProductId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'instancesId' field.
      * @return The value.
      */
    public java.lang.Long getInstancesId() {
      return instancesId;
    }

    /**
      * Sets the value of the 'instancesId' field.
      * @param value The value of 'instancesId'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder setInstancesId(long value) {
      validate(fields()[1], value);
      this.instancesId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'instancesId' field has been set.
      * @return True if the 'instancesId' field has been set, false otherwise.
      */
    public boolean hasInstancesId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'instancesId' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO.Builder clearInstancesId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AssociatedProductInstancesAVRO build() {
      try {
        AssociatedProductInstancesAVRO record = new AssociatedProductInstancesAVRO();
        record.quotationProductId = fieldSetFlags()[0] ? this.quotationProductId : (java.lang.Long) defaultValue(fields()[0]);
        record.instancesId = fieldSetFlags()[1] ? this.instancesId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AssociatedProductInstancesAVRO>
    WRITER$ = (org.apache.avro.io.DatumWriter<AssociatedProductInstancesAVRO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AssociatedProductInstancesAVRO>
    READER$ = (org.apache.avro.io.DatumReader<AssociatedProductInstancesAVRO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
