/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alianca.intercab.emp.quotation;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IntercabQuotation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7175097103734517965L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IntercabQuotation\",\"namespace\":\"com.alianca.intercab.emp.quotation\",\"fields\":[{\"name\":\"quotationId\",\"type\":\"long\"},{\"name\":\"clientName\",\"type\":\"string\"},{\"name\":\"statusQuotation\",\"type\":\"long\"},{\"name\":\"portOfLoad\",\"type\":\"string\"},{\"name\":\"portOfDischarge\",\"type\":\"long\"},{\"name\":\"portOfTransshipment\",\"type\":\"string\"},{\"name\":\"size\",\"type\":\"string\"},{\"name\":\"equipmentType\",\"type\":\"string\"},{\"name\":\"ownership\",\"type\":\"string\"},{\"name\":\"rateCurrency\",\"type\":\"string\"},{\"name\":\"action\",\"type\":\"string\"},{\"name\":\"quotationDateFrom\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"customerType\",\"type\":\"string\"},{\"name\":\"associatedProducts\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AssociatedProductsAVRO\",\"fields\":[{\"name\":\"quotationId\",\"type\":\"long\"},{\"name\":\"productId\",\"type\":\"long\"}]}}},{\"name\":\"associatedProductInstances\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AssociatedProductInstancesAVRO\",\"fields\":[{\"name\":\"quotationProductId\",\"type\":\"long\"},{\"name\":\"instancesId\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IntercabQuotation> ENCODER =
      new BinaryMessageEncoder<IntercabQuotation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IntercabQuotation> DECODER =
      new BinaryMessageDecoder<IntercabQuotation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<IntercabQuotation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<IntercabQuotation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IntercabQuotation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this IntercabQuotation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a IntercabQuotation from a ByteBuffer. */
  public static IntercabQuotation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long quotationId;
  @Deprecated public java.lang.CharSequence clientName;
  @Deprecated public long statusQuotation;
  @Deprecated public java.lang.CharSequence portOfLoad;
  @Deprecated public long portOfDischarge;
  @Deprecated public java.lang.CharSequence portOfTransshipment;
  @Deprecated public java.lang.CharSequence size;
  @Deprecated public java.lang.CharSequence equipmentType;
  @Deprecated public java.lang.CharSequence ownership;
  @Deprecated public java.lang.CharSequence rateCurrency;
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public org.joda.time.LocalDate quotationDateFrom;
  @Deprecated public java.lang.CharSequence customerType;
  @Deprecated public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> associatedProducts;
  @Deprecated public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> associatedProductInstances;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IntercabQuotation() {}

  /**
   * All-args constructor.
   * @param quotationId The new value for quotationId
   * @param clientName The new value for clientName
   * @param statusQuotation The new value for statusQuotation
   * @param portOfLoad The new value for portOfLoad
   * @param portOfDischarge The new value for portOfDischarge
   * @param portOfTransshipment The new value for portOfTransshipment
   * @param size The new value for size
   * @param equipmentType The new value for equipmentType
   * @param ownership The new value for ownership
   * @param rateCurrency The new value for rateCurrency
   * @param action The new value for action
   * @param quotationDateFrom The new value for quotationDateFrom
   * @param customerType The new value for customerType
   * @param associatedProducts The new value for associatedProducts
   * @param associatedProductInstances The new value for associatedProductInstances
   */
  public IntercabQuotation(java.lang.Long quotationId, java.lang.CharSequence clientName, java.lang.Long statusQuotation, java.lang.CharSequence portOfLoad, java.lang.Long portOfDischarge, java.lang.CharSequence portOfTransshipment, java.lang.CharSequence size, java.lang.CharSequence equipmentType, java.lang.CharSequence ownership, java.lang.CharSequence rateCurrency, java.lang.CharSequence action, org.joda.time.LocalDate quotationDateFrom, java.lang.CharSequence customerType, java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> associatedProducts, java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> associatedProductInstances) {
    this.quotationId = quotationId;
    this.clientName = clientName;
    this.statusQuotation = statusQuotation;
    this.portOfLoad = portOfLoad;
    this.portOfDischarge = portOfDischarge;
    this.portOfTransshipment = portOfTransshipment;
    this.size = size;
    this.equipmentType = equipmentType;
    this.ownership = ownership;
    this.rateCurrency = rateCurrency;
    this.action = action;
    this.quotationDateFrom = quotationDateFrom;
    this.customerType = customerType;
    this.associatedProducts = associatedProducts;
    this.associatedProductInstances = associatedProductInstances;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return quotationId;
    case 1: return clientName;
    case 2: return statusQuotation;
    case 3: return portOfLoad;
    case 4: return portOfDischarge;
    case 5: return portOfTransshipment;
    case 6: return size;
    case 7: return equipmentType;
    case 8: return ownership;
    case 9: return rateCurrency;
    case 10: return action;
    case 11: return quotationDateFrom;
    case 12: return customerType;
    case 13: return associatedProducts;
    case 14: return associatedProductInstances;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      DATE_CONVERSION,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: quotationId = (java.lang.Long)value$; break;
    case 1: clientName = (java.lang.CharSequence)value$; break;
    case 2: statusQuotation = (java.lang.Long)value$; break;
    case 3: portOfLoad = (java.lang.CharSequence)value$; break;
    case 4: portOfDischarge = (java.lang.Long)value$; break;
    case 5: portOfTransshipment = (java.lang.CharSequence)value$; break;
    case 6: size = (java.lang.CharSequence)value$; break;
    case 7: equipmentType = (java.lang.CharSequence)value$; break;
    case 8: ownership = (java.lang.CharSequence)value$; break;
    case 9: rateCurrency = (java.lang.CharSequence)value$; break;
    case 10: action = (java.lang.CharSequence)value$; break;
    case 11: quotationDateFrom = (org.joda.time.LocalDate)value$; break;
    case 12: customerType = (java.lang.CharSequence)value$; break;
    case 13: associatedProducts = (java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO>)value$; break;
    case 14: associatedProductInstances = (java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'quotationId' field.
   * @return The value of the 'quotationId' field.
   */
  public java.lang.Long getQuotationId() {
    return quotationId;
  }

  /**
   * Sets the value of the 'quotationId' field.
   * @param value the value to set.
   */
  public void setQuotationId(java.lang.Long value) {
    this.quotationId = value;
  }

  /**
   * Gets the value of the 'clientName' field.
   * @return The value of the 'clientName' field.
   */
  public java.lang.CharSequence getClientName() {
    return clientName;
  }

  /**
   * Sets the value of the 'clientName' field.
   * @param value the value to set.
   */
  public void setClientName(java.lang.CharSequence value) {
    this.clientName = value;
  }

  /**
   * Gets the value of the 'statusQuotation' field.
   * @return The value of the 'statusQuotation' field.
   */
  public java.lang.Long getStatusQuotation() {
    return statusQuotation;
  }

  /**
   * Sets the value of the 'statusQuotation' field.
   * @param value the value to set.
   */
  public void setStatusQuotation(java.lang.Long value) {
    this.statusQuotation = value;
  }

  /**
   * Gets the value of the 'portOfLoad' field.
   * @return The value of the 'portOfLoad' field.
   */
  public java.lang.CharSequence getPortOfLoad() {
    return portOfLoad;
  }

  /**
   * Sets the value of the 'portOfLoad' field.
   * @param value the value to set.
   */
  public void setPortOfLoad(java.lang.CharSequence value) {
    this.portOfLoad = value;
  }

  /**
   * Gets the value of the 'portOfDischarge' field.
   * @return The value of the 'portOfDischarge' field.
   */
  public java.lang.Long getPortOfDischarge() {
    return portOfDischarge;
  }

  /**
   * Sets the value of the 'portOfDischarge' field.
   * @param value the value to set.
   */
  public void setPortOfDischarge(java.lang.Long value) {
    this.portOfDischarge = value;
  }

  /**
   * Gets the value of the 'portOfTransshipment' field.
   * @return The value of the 'portOfTransshipment' field.
   */
  public java.lang.CharSequence getPortOfTransshipment() {
    return portOfTransshipment;
  }

  /**
   * Sets the value of the 'portOfTransshipment' field.
   * @param value the value to set.
   */
  public void setPortOfTransshipment(java.lang.CharSequence value) {
    this.portOfTransshipment = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public java.lang.CharSequence getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.CharSequence value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'equipmentType' field.
   * @return The value of the 'equipmentType' field.
   */
  public java.lang.CharSequence getEquipmentType() {
    return equipmentType;
  }

  /**
   * Sets the value of the 'equipmentType' field.
   * @param value the value to set.
   */
  public void setEquipmentType(java.lang.CharSequence value) {
    this.equipmentType = value;
  }

  /**
   * Gets the value of the 'ownership' field.
   * @return The value of the 'ownership' field.
   */
  public java.lang.CharSequence getOwnership() {
    return ownership;
  }

  /**
   * Sets the value of the 'ownership' field.
   * @param value the value to set.
   */
  public void setOwnership(java.lang.CharSequence value) {
    this.ownership = value;
  }

  /**
   * Gets the value of the 'rateCurrency' field.
   * @return The value of the 'rateCurrency' field.
   */
  public java.lang.CharSequence getRateCurrency() {
    return rateCurrency;
  }

  /**
   * Sets the value of the 'rateCurrency' field.
   * @param value the value to set.
   */
  public void setRateCurrency(java.lang.CharSequence value) {
    this.rateCurrency = value;
  }

  /**
   * Gets the value of the 'action' field.
   * @return The value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'quotationDateFrom' field.
   * @return The value of the 'quotationDateFrom' field.
   */
  public org.joda.time.LocalDate getQuotationDateFrom() {
    return quotationDateFrom;
  }

  /**
   * Sets the value of the 'quotationDateFrom' field.
   * @param value the value to set.
   */
  public void setQuotationDateFrom(org.joda.time.LocalDate value) {
    this.quotationDateFrom = value;
  }

  /**
   * Gets the value of the 'customerType' field.
   * @return The value of the 'customerType' field.
   */
  public java.lang.CharSequence getCustomerType() {
    return customerType;
  }

  /**
   * Sets the value of the 'customerType' field.
   * @param value the value to set.
   */
  public void setCustomerType(java.lang.CharSequence value) {
    this.customerType = value;
  }

  /**
   * Gets the value of the 'associatedProducts' field.
   * @return The value of the 'associatedProducts' field.
   */
  public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> getAssociatedProducts() {
    return associatedProducts;
  }

  /**
   * Sets the value of the 'associatedProducts' field.
   * @param value the value to set.
   */
  public void setAssociatedProducts(java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> value) {
    this.associatedProducts = value;
  }

  /**
   * Gets the value of the 'associatedProductInstances' field.
   * @return The value of the 'associatedProductInstances' field.
   */
  public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> getAssociatedProductInstances() {
    return associatedProductInstances;
  }

  /**
   * Sets the value of the 'associatedProductInstances' field.
   * @param value the value to set.
   */
  public void setAssociatedProductInstances(java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> value) {
    this.associatedProductInstances = value;
  }

  /**
   * Creates a new IntercabQuotation RecordBuilder.
   * @return A new IntercabQuotation RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.IntercabQuotation.Builder newBuilder() {
    return new com.alianca.intercab.emp.quotation.IntercabQuotation.Builder();
  }

  /**
   * Creates a new IntercabQuotation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IntercabQuotation RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.IntercabQuotation.Builder newBuilder(com.alianca.intercab.emp.quotation.IntercabQuotation.Builder other) {
    return new com.alianca.intercab.emp.quotation.IntercabQuotation.Builder(other);
  }

  /**
   * Creates a new IntercabQuotation RecordBuilder by copying an existing IntercabQuotation instance.
   * @param other The existing instance to copy.
   * @return A new IntercabQuotation RecordBuilder
   */
  public static com.alianca.intercab.emp.quotation.IntercabQuotation.Builder newBuilder(com.alianca.intercab.emp.quotation.IntercabQuotation other) {
    return new com.alianca.intercab.emp.quotation.IntercabQuotation.Builder(other);
  }

  /**
   * RecordBuilder for IntercabQuotation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IntercabQuotation>
    implements org.apache.avro.data.RecordBuilder<IntercabQuotation> {

    private long quotationId;
    private java.lang.CharSequence clientName;
    private long statusQuotation;
    private java.lang.CharSequence portOfLoad;
    private long portOfDischarge;
    private java.lang.CharSequence portOfTransshipment;
    private java.lang.CharSequence size;
    private java.lang.CharSequence equipmentType;
    private java.lang.CharSequence ownership;
    private java.lang.CharSequence rateCurrency;
    private java.lang.CharSequence action;
    private org.joda.time.LocalDate quotationDateFrom;
    private java.lang.CharSequence customerType;
    private java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> associatedProducts;
    private java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> associatedProductInstances;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alianca.intercab.emp.quotation.IntercabQuotation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.quotationId)) {
        this.quotationId = data().deepCopy(fields()[0].schema(), other.quotationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clientName)) {
        this.clientName = data().deepCopy(fields()[1].schema(), other.clientName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.statusQuotation)) {
        this.statusQuotation = data().deepCopy(fields()[2].schema(), other.statusQuotation);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.portOfLoad)) {
        this.portOfLoad = data().deepCopy(fields()[3].schema(), other.portOfLoad);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.portOfDischarge)) {
        this.portOfDischarge = data().deepCopy(fields()[4].schema(), other.portOfDischarge);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.portOfTransshipment)) {
        this.portOfTransshipment = data().deepCopy(fields()[5].schema(), other.portOfTransshipment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.size)) {
        this.size = data().deepCopy(fields()[6].schema(), other.size);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.equipmentType)) {
        this.equipmentType = data().deepCopy(fields()[7].schema(), other.equipmentType);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ownership)) {
        this.ownership = data().deepCopy(fields()[8].schema(), other.ownership);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.rateCurrency)) {
        this.rateCurrency = data().deepCopy(fields()[9].schema(), other.rateCurrency);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.action)) {
        this.action = data().deepCopy(fields()[10].schema(), other.action);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.quotationDateFrom)) {
        this.quotationDateFrom = data().deepCopy(fields()[11].schema(), other.quotationDateFrom);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.customerType)) {
        this.customerType = data().deepCopy(fields()[12].schema(), other.customerType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.associatedProducts)) {
        this.associatedProducts = data().deepCopy(fields()[13].schema(), other.associatedProducts);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.associatedProductInstances)) {
        this.associatedProductInstances = data().deepCopy(fields()[14].schema(), other.associatedProductInstances);
        fieldSetFlags()[14] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing IntercabQuotation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alianca.intercab.emp.quotation.IntercabQuotation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.quotationId)) {
        this.quotationId = data().deepCopy(fields()[0].schema(), other.quotationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clientName)) {
        this.clientName = data().deepCopy(fields()[1].schema(), other.clientName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.statusQuotation)) {
        this.statusQuotation = data().deepCopy(fields()[2].schema(), other.statusQuotation);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.portOfLoad)) {
        this.portOfLoad = data().deepCopy(fields()[3].schema(), other.portOfLoad);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.portOfDischarge)) {
        this.portOfDischarge = data().deepCopy(fields()[4].schema(), other.portOfDischarge);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.portOfTransshipment)) {
        this.portOfTransshipment = data().deepCopy(fields()[5].schema(), other.portOfTransshipment);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.size)) {
        this.size = data().deepCopy(fields()[6].schema(), other.size);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.equipmentType)) {
        this.equipmentType = data().deepCopy(fields()[7].schema(), other.equipmentType);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ownership)) {
        this.ownership = data().deepCopy(fields()[8].schema(), other.ownership);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.rateCurrency)) {
        this.rateCurrency = data().deepCopy(fields()[9].schema(), other.rateCurrency);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.action)) {
        this.action = data().deepCopy(fields()[10].schema(), other.action);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.quotationDateFrom)) {
        this.quotationDateFrom = data().deepCopy(fields()[11].schema(), other.quotationDateFrom);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.customerType)) {
        this.customerType = data().deepCopy(fields()[12].schema(), other.customerType);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.associatedProducts)) {
        this.associatedProducts = data().deepCopy(fields()[13].schema(), other.associatedProducts);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.associatedProductInstances)) {
        this.associatedProductInstances = data().deepCopy(fields()[14].schema(), other.associatedProductInstances);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'quotationId' field.
      * @return The value.
      */
    public java.lang.Long getQuotationId() {
      return quotationId;
    }

    /**
      * Sets the value of the 'quotationId' field.
      * @param value The value of 'quotationId'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setQuotationId(long value) {
      validate(fields()[0], value);
      this.quotationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'quotationId' field has been set.
      * @return True if the 'quotationId' field has been set, false otherwise.
      */
    public boolean hasQuotationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'quotationId' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearQuotationId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'clientName' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientName() {
      return clientName;
    }

    /**
      * Sets the value of the 'clientName' field.
      * @param value The value of 'clientName'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setClientName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.clientName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'clientName' field has been set.
      * @return True if the 'clientName' field has been set, false otherwise.
      */
    public boolean hasClientName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'clientName' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearClientName() {
      clientName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'statusQuotation' field.
      * @return The value.
      */
    public java.lang.Long getStatusQuotation() {
      return statusQuotation;
    }

    /**
      * Sets the value of the 'statusQuotation' field.
      * @param value The value of 'statusQuotation'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setStatusQuotation(long value) {
      validate(fields()[2], value);
      this.statusQuotation = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'statusQuotation' field has been set.
      * @return True if the 'statusQuotation' field has been set, false otherwise.
      */
    public boolean hasStatusQuotation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'statusQuotation' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearStatusQuotation() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'portOfLoad' field.
      * @return The value.
      */
    public java.lang.CharSequence getPortOfLoad() {
      return portOfLoad;
    }

    /**
      * Sets the value of the 'portOfLoad' field.
      * @param value The value of 'portOfLoad'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setPortOfLoad(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.portOfLoad = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'portOfLoad' field has been set.
      * @return True if the 'portOfLoad' field has been set, false otherwise.
      */
    public boolean hasPortOfLoad() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'portOfLoad' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearPortOfLoad() {
      portOfLoad = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'portOfDischarge' field.
      * @return The value.
      */
    public java.lang.Long getPortOfDischarge() {
      return portOfDischarge;
    }

    /**
      * Sets the value of the 'portOfDischarge' field.
      * @param value The value of 'portOfDischarge'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setPortOfDischarge(long value) {
      validate(fields()[4], value);
      this.portOfDischarge = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'portOfDischarge' field has been set.
      * @return True if the 'portOfDischarge' field has been set, false otherwise.
      */
    public boolean hasPortOfDischarge() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'portOfDischarge' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearPortOfDischarge() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'portOfTransshipment' field.
      * @return The value.
      */
    public java.lang.CharSequence getPortOfTransshipment() {
      return portOfTransshipment;
    }

    /**
      * Sets the value of the 'portOfTransshipment' field.
      * @param value The value of 'portOfTransshipment'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setPortOfTransshipment(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.portOfTransshipment = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'portOfTransshipment' field has been set.
      * @return True if the 'portOfTransshipment' field has been set, false otherwise.
      */
    public boolean hasPortOfTransshipment() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'portOfTransshipment' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearPortOfTransshipment() {
      portOfTransshipment = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public java.lang.CharSequence getSize() {
      return size;
    }

    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setSize(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.size = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearSize() {
      size = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'equipmentType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEquipmentType() {
      return equipmentType;
    }

    /**
      * Sets the value of the 'equipmentType' field.
      * @param value The value of 'equipmentType'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setEquipmentType(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.equipmentType = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'equipmentType' field has been set.
      * @return True if the 'equipmentType' field has been set, false otherwise.
      */
    public boolean hasEquipmentType() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'equipmentType' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearEquipmentType() {
      equipmentType = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'ownership' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnership() {
      return ownership;
    }

    /**
      * Sets the value of the 'ownership' field.
      * @param value The value of 'ownership'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setOwnership(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.ownership = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'ownership' field has been set.
      * @return True if the 'ownership' field has been set, false otherwise.
      */
    public boolean hasOwnership() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'ownership' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearOwnership() {
      ownership = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'rateCurrency' field.
      * @return The value.
      */
    public java.lang.CharSequence getRateCurrency() {
      return rateCurrency;
    }

    /**
      * Sets the value of the 'rateCurrency' field.
      * @param value The value of 'rateCurrency'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setRateCurrency(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.rateCurrency = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'rateCurrency' field has been set.
      * @return True if the 'rateCurrency' field has been set, false otherwise.
      */
    public boolean hasRateCurrency() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'rateCurrency' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearRateCurrency() {
      rateCurrency = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'action' field.
      * @return The value.
      */
    public java.lang.CharSequence getAction() {
      return action;
    }

    /**
      * Sets the value of the 'action' field.
      * @param value The value of 'action'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.action = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'action' field has been set.
      * @return True if the 'action' field has been set, false otherwise.
      */
    public boolean hasAction() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'action' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearAction() {
      action = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'quotationDateFrom' field.
      * @return The value.
      */
    public org.joda.time.LocalDate getQuotationDateFrom() {
      return quotationDateFrom;
    }

    /**
      * Sets the value of the 'quotationDateFrom' field.
      * @param value The value of 'quotationDateFrom'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setQuotationDateFrom(org.joda.time.LocalDate value) {
      validate(fields()[11], value);
      this.quotationDateFrom = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'quotationDateFrom' field has been set.
      * @return True if the 'quotationDateFrom' field has been set, false otherwise.
      */
    public boolean hasQuotationDateFrom() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'quotationDateFrom' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearQuotationDateFrom() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerType' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerType() {
      return customerType;
    }

    /**
      * Sets the value of the 'customerType' field.
      * @param value The value of 'customerType'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setCustomerType(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.customerType = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'customerType' field has been set.
      * @return True if the 'customerType' field has been set, false otherwise.
      */
    public boolean hasCustomerType() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'customerType' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearCustomerType() {
      customerType = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedProducts' field.
      * @return The value.
      */
    public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> getAssociatedProducts() {
      return associatedProducts;
    }

    /**
      * Sets the value of the 'associatedProducts' field.
      * @param value The value of 'associatedProducts'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setAssociatedProducts(java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO> value) {
      validate(fields()[13], value);
      this.associatedProducts = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'associatedProducts' field has been set.
      * @return True if the 'associatedProducts' field has been set, false otherwise.
      */
    public boolean hasAssociatedProducts() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'associatedProducts' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearAssociatedProducts() {
      associatedProducts = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedProductInstances' field.
      * @return The value.
      */
    public java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> getAssociatedProductInstances() {
      return associatedProductInstances;
    }

    /**
      * Sets the value of the 'associatedProductInstances' field.
      * @param value The value of 'associatedProductInstances'.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder setAssociatedProductInstances(java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO> value) {
      validate(fields()[14], value);
      this.associatedProductInstances = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'associatedProductInstances' field has been set.
      * @return True if the 'associatedProductInstances' field has been set, false otherwise.
      */
    public boolean hasAssociatedProductInstances() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'associatedProductInstances' field.
      * @return This builder.
      */
    public com.alianca.intercab.emp.quotation.IntercabQuotation.Builder clearAssociatedProductInstances() {
      associatedProductInstances = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IntercabQuotation build() {
      try {
        IntercabQuotation record = new IntercabQuotation();
        record.quotationId = fieldSetFlags()[0] ? this.quotationId : (java.lang.Long) defaultValue(fields()[0], record.getConversion(0));
        record.clientName = fieldSetFlags()[1] ? this.clientName : (java.lang.CharSequence) defaultValue(fields()[1], record.getConversion(1));
        record.statusQuotation = fieldSetFlags()[2] ? this.statusQuotation : (java.lang.Long) defaultValue(fields()[2], record.getConversion(2));
        record.portOfLoad = fieldSetFlags()[3] ? this.portOfLoad : (java.lang.CharSequence) defaultValue(fields()[3], record.getConversion(3));
        record.portOfDischarge = fieldSetFlags()[4] ? this.portOfDischarge : (java.lang.Long) defaultValue(fields()[4], record.getConversion(4));
        record.portOfTransshipment = fieldSetFlags()[5] ? this.portOfTransshipment : (java.lang.CharSequence) defaultValue(fields()[5], record.getConversion(5));
        record.size = fieldSetFlags()[6] ? this.size : (java.lang.CharSequence) defaultValue(fields()[6], record.getConversion(6));
        record.equipmentType = fieldSetFlags()[7] ? this.equipmentType : (java.lang.CharSequence) defaultValue(fields()[7], record.getConversion(7));
        record.ownership = fieldSetFlags()[8] ? this.ownership : (java.lang.CharSequence) defaultValue(fields()[8], record.getConversion(8));
        record.rateCurrency = fieldSetFlags()[9] ? this.rateCurrency : (java.lang.CharSequence) defaultValue(fields()[9], record.getConversion(9));
        record.action = fieldSetFlags()[10] ? this.action : (java.lang.CharSequence) defaultValue(fields()[10], record.getConversion(10));
        record.quotationDateFrom = fieldSetFlags()[11] ? this.quotationDateFrom : (org.joda.time.LocalDate) defaultValue(fields()[11], record.getConversion(11));
        record.customerType = fieldSetFlags()[12] ? this.customerType : (java.lang.CharSequence) defaultValue(fields()[12], record.getConversion(12));
        record.associatedProducts = fieldSetFlags()[13] ? this.associatedProducts : (java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductsAVRO>) defaultValue(fields()[13], record.getConversion(13));
        record.associatedProductInstances = fieldSetFlags()[14] ? this.associatedProductInstances : (java.util.List<com.alianca.intercab.emp.quotation.AssociatedProductInstancesAVRO>) defaultValue(fields()[14], record.getConversion(14));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IntercabQuotation>
    WRITER$ = (org.apache.avro.io.DatumWriter<IntercabQuotation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IntercabQuotation>
    READER$ = (org.apache.avro.io.DatumReader<IntercabQuotation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
